version: "3.9"
services:
  db:
    container_name: db-examenweb
    image: mysql:8.0
    ports:
      - "3307:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: examenweb_db
      MYSQL_USER: examenweb
      MYSQL_PASSWORD: 123456
    networks:
      - net-examenweb
  web:
    container_name: web-examenweb
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - "./web:/var/www/html"
      - "./httpd.conf:/etc/httpd/conf/httpd.conf"
    image: laravel-php8
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - net-examenweb
networks:
  net-examenweb:
    
